allowBuilds:
  esbuild: true
  sharp: true
  workerd: true

catalogMode: prefer
cleanupUnusedCatalogs: true
shellEmulator: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - astro-mermaid@2.0.1
  - chokidar@4.0.3
  - semver@6.3.1
  - undici-types@6.21.0
